discord-link: "https://discord.gg/pandaverse"
requirements:
  - "&8* &fחובה להיות בשרת הדיסקורד שלנו!"
  - "&8* &fהעלאת תוכן איכותי (סרטונים / שידורים חיים)."
  - "&8* &fמינימום צפיות או עוקבים סביר."
